### PR TITLE
PCI, SATA, libc

### PR DESCRIPTION
**Pull request by drsn0w**
### Additions
- Basic PCI informational functions
- PCI device enumeration at boot
### Issues
- PCI enumeration debug messages cause a race condition in the terminal driver, therefore use kernel_thread to pause for 1 second after printing each message
- Currently we just bruteforce the PCI busses. Eventually can be updated to actually traverse the busses and set them up too!
### Additions
- Some header declarations
### Issues
- None
### Additions
- add in `%x` support to printf
### Issues
- None found

### CODE REVIEW

**Comment by shawnanastasio** [comment]
Does not compile. Looks to be an issue with `PCI_CLASS_IDS` in one of your header files.

```
kernel/kernel.o:(.data+0x120): multiple definition of `PCI_CLASS_IDS'
drivers/pci/pci.o:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
Makefile:62: recipe for target 'shawnos.kernel' failed
```

**Comment by drsn0w** [comment]
Issue was fixed by you

**Comment by shawnanastasio** [comment]
Merged.

**Comment by drsn0w** [comment]
You don't need2comment Merged it says it in the thing0

**Pull request merged**
